---

#- name: Plan the creation of the ec2 server
 # terraform:
  #  project_path: '{{ playbook_dir }}'
  #  plan_file: 'amazon.tf'
  #  lock: true
  #  state: planned

- name: Create ec2 server for VPN  
  terraform:
    project_path: '{{ playbook_dir }}'
    state: present

- include_vars:
        file: terraform.tfstate
        name: tfstate
  
- debug: var=tfstate.modules[0].resources["aws_instance.outline_vpn_server"].primary.attributes.public_ip

#- hosts: "{{ tfstate.modules[0].resources[aws_instance.outline_vpn_server].primary.attributes.public_ip }}"
#  remote_user: centos
#  become: yes 
 
 
 #- name: ensure a list of packages installed
 # yum:
 #   name: "{{ packages }}"
 # vars:
 #   packages:
 #   - wget
 #   - docker


#- name: Destroy the ec2 server for VPN
#  terraform:
#    project_path: '{{ playbook_dir }}'
#    lock: true
#    state: absent

#TODO: Ensure that terraform plan/apply/delete output is visible through ansible. 
#TODO: Be able to collect details from terraform output and use to configure server
